---
k3s_cluster:
  children:
    server:
      hosts:
        SERVER_IP:
    agent:
      hosts:
        AGENT_IP:
  vars:
    ansible_port: 22
    ansible_user: ubuntu
    k3s_version: v1.30.2+k3s1
    token: "0123456789"
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
    extra_server_args: ""
    extra_agent_args: ""
    ansible_ssh_private_key_file: /tmp/id_ed25519
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_python_interpreter: "/usr/bin/python3"
