name: 'Terraform CI/CD'

on:
  push:
    branches:
      - task_1
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform CI/CD'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'eu-central-1'
      TF_VERSION: '1.6.0'

    defaults:
      run:
        working-directory: tasks/task-1
    steps:
      - name: 'Checkout GitHub repository'
        uses: actions/checkout@v2

      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false
      
      - name: Terraform Format
        id: fmt
        working-directory: tasks/task_1
        run: terraform fmt -check

      - name: 'Terraform Init'
        id: init
        working-directory: tasks/task_1
        run: terraform init

      - name: 'Terraform Plan'
        id: plan
        working-directory: tasks/task_1
        run: terraform init && terraform plan

      - name: 'Terraform Apply'
        working-directory: tasks/task_1
        run: terraform init && terraform apply -auto-approve